# Generated by Django 5.1.6 on 2025-02-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clase",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
